version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Release


#  - nuget install packages.config

build:
  #include_nuget_references: true
  verbosity: normal
  project: SilkWrapperNET.sln 


 