version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Release


before_build: 
    - ps: Set-Location "C:/projects/silkwrappernet/PS"
    - ps: ./Build_PDFium.ps1 -Arch x64


build_script:
    - ps: Set-Location "C:/projects/silkwrappernet/PS"
    - ps: ./Build_Wrapper.ps1 -Arch x64

 