version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Release


before_build: 
    - ps: Set-Location "C:/projects/silkwrappernet/PS"
     

build:
  #include_nuget_references: true
  verbosity: normal
  project: SilkWrapperNET.sln 


 